### ISSUE TITLE
log level never considered under INFO level.

### ISSUE THREAD

**Issue by giupo** [WLOGSolutions/r-logging#1]
Whenever I try to lower the logging level from INFO (20), I'm never able to printout messages passed to logdebug, logfine, etc...

test case:

``` R
> library(logging)
> basicConfig("DEBUG")  # or something lower than 20
> getLogger()
Reference class object of class "Logger"
Field "name":
[1] ""
Field "handlers":
$basic.stdout
<environment: 0x9e23c8c>

Field "level":
DEBUG 
   10 
> loginfo("info")
2013-02-07 11:48:29 INFO::info # ok, as I expected...
> logdebug("debug") # ... shouldn't I see the debug message here?
> logReset() # let's see if at higher levels works
> basicConfig("ERROR")
> getLogger()
Reference class object of class "Logger"
Field "name":
[1] ""
Field "handlers":
$basic.stdout
<environment: 0x8d64934>

Field "level":
ERROR 
   40 
> loginfo("info")
> logwarn("warn")
> logerror("error")
2013-02-07 11:50:05 ERROR::error # no problems here.
```

The version I'm using through CRAN is 0.6-92, maybe I should update from here ;)

HTH, 
Giuseppe

**Comment by mfrasca** [comment]
if I recall correctly, and given your tests, `basicConfig` uses the `level` parameter to set the level of the root logger.
the level of the console handler is not influenced by this.
set the level of the console handler and things will work as expected.

on the other hand, maybe the `level` parameter should really be setting the level of the console handler...
I just received an other request in the same direction, but on r-forge.

https://r-forge.r-project.org/tracker/index.php?func=detail&aid=2537&group_id=672&atid=2707

**Comment by giupo** [comment]
Thank you!
Giuseppe
