### ISSUE TITLE
Error when package 'methods' is not attached (R 3.3)

### ISSUE THREAD

**Issue by clhunsen** [WLOGSolutions/r-logging#1]
I have a problem with the newest version of the `logging` package (`0.8-104`) while using R 3.3. When running analysis scripts using `Rscript` (instead of `R`), an error is thrown:

> Error in UseMethod("updateOptions") : 
  no applicable method for 'updateOptions' applied to an object of class "Logger"
Calls: <Anonymous> -> updateOptions

I do not know what changed exactly from the previous version to raise this error, I just noticed that our TravisCI script broke without changing any R defaults.

#### MWE

I installed `logging` in a `packrat` environment first to guarantee reproducibilty and avoid side effects:
```bash
R -e "packrat::init(); install.packages('logging');"
```

Then, I created a script file `test.R`:
```R
library("logging")
sessionInfo() # output of attached packages
logging::basicConfig()
print("foo") # error check
```

When running the script via `Rscript test.R`, I get the following output indicating an error:
> R version 3.3.3 (2017-03-06)
> Platform: x86_64-pc-linux-gnu (64-bit)
> Running under: Debian GNU/Linux 9 (stretch)
> 
> locale:
>  [1] LC_CTYPE=en_IE.UTF-8       LC_NUMERIC=C              
>  [3] LC_TIME=en_IE.UTF-8        LC_COLLATE=en_IE.UTF-8    
>  [5] LC_MONETARY=en_IE.UTF-8    LC_MESSAGES=en_IE.UTF-8   
>  [7] LC_PAPER=en_IE.UTF-8       LC_NAME=C                 
>  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
> [11] LC_MEASUREMENT=en_IE.UTF-8 LC_IDENTIFICATION=C       
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  base     
> 
> other attached packages:
> [1] logging_0.8-104
> 
> loaded via a namespace (and not attached):
> [1] tools_3.3.3     methods_3.3.3   packrat_0.4.9-3
> Error in UseMethod("updateOptions") : 
>   no applicable method for 'updateOptions' applied to an object of class "Logger"
> Calls: <Anonymous> -> updateOptions
>
> Execution halted

#### Problem

The error occurs because the base package `methods` is not attached properly (it is only loaded via its namespace). This is the default behavior as documented in `?Rscript`:
> The default for Rscript omits *methods* as it takes about 60% of the startup time.

This does not occur when using R 3.5 (as the base package `methods` is then attached by default) or running the script via the command `R --no-save < test.R` under R 3.3:
> R version 3.3.3 (2017-03-06) -- "Another Canoe"
> [...] 
> \> library(logging)
> \> sessionInfo() # output of attached packages
> R version 3.3.3 (2017-03-06)
> Platform: x86_64-pc-linux-gnu (64-bit)
> Running under: Debian GNU/Linux 9 (stretch)
> 
> locale:
>  [1] LC_CTYPE=en_IE.UTF-8       LC_NUMERIC=C              
>  [3] LC_TIME=en_IE.UTF-8        LC_COLLATE=en_IE.UTF-8    
>  [5] LC_MONETARY=en_IE.UTF-8    LC_MESSAGES=en_IE.UTF-8   
>  [7] LC_PAPER=en_IE.UTF-8       LC_NAME=C                 
>  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
> [11] LC_MEASUREMENT=en_IE.UTF-8 LC_IDENTIFICATION=C       
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] logging_0.8-104
> 
> loaded via a namespace (and not attached):
> [1] tools_3.3.3     packrat_0.4.9-3
> \> logging::basicConfig()
> \> print("foo") # error check
> [1] "foo"
> 

#### Affected versions

As far as I debugged the problem, only logging `0.8-104` is affected – with R < 3.5. The previous version `0.7-103` works fine.

------------------------

Is there any way for you to solve this problem in-package?

**Comment by ws171913** [comment]
Thank you for detailed description of issue.

I've manage to reproduce it. Couple of remarks:
1. issue seems to be exist in previous version also: 
```
root@e733c586a3e8:/opt# Rscript --vanilla -e "R.version.string; readLines('/etc/debian_version'); packageVersion('logging'); logging::basicConfig()"
[1] "R version 3.3.3 (2017-03-06)"
[1] "8.10"
[1] ‘0.7.103’
Error in UseMethod("updateOptions") :
  no applicable method for 'updateOptions' applied to an object of class "Logger"
Calls: <Anonymous> -> updateOptions
Execution halted
```
2. Affected versions: R < 3.4. For R3.4 logging 0.8-104 works properly:
```
root@b5b54d8de98b:/opt# Rscript --vanilla -e "R.version.string; readLines('/etc/debian_version'); packageVersion('logging'); logging::basicConfig(); logging::loginfo('asd')"
[1] "R version 3.4.2 (2017-09-28)"
[1] "9.2"
[1] ‘0.8.104’
2019-01-16 14:49:29 INFO::asd
root@b5b54d8de98b:/opt#
```

Problem detected, fix is prepared. Today(16.01.2019) it will be submitted to CRAN. Hope it will be processed and exposed in short time.

Best regards

**Comment by ws171913** [comment]
@clhunsen Hello again. I've got message from CRAN: "thanks, package logging_0.9-105.tar.gz is on its way to CRAN."

Please, let me know as soon as you check that the issue have been resolved

**Comment by clhunsen** [comment]
I ran my test script with version `0.9-105` installed and it worked properly. Thank you very much for the quick fix, @ws171913. :+1:
