### ISSUE TITLE
using 'as.environment(NULL)' is defunct

### ISSUE THREAD

**Issue by mfrasca** [WLOGSolutions/r-logging#18]
from an email (Paul Roebuck, 2014-10-03)

this doesn't appear to work anymore (logging 0.7-103)...

```
R> setLevel(30, getHandler('basic.stdout'))
Error in as.environment(pos) : using 'as.environment(NULL)' is defunct
```

**Comment by ws171913** [comment]
Fixed in v0.9 as far as I remember.
@mfrasca Close the issue, please
