### ISSUE TITLE
leading whitespace in msg

### ISSUE THREAD

**Issue by yitang** [WLOGSolutions/r-logging#20]
Hi, thanks for writing this logging package.

I just realised the leading whitespaces in a message are trimmed, I am not sure if it is a bug or a feature, but wonder if there's a way to preserve those whitespaces? 

``` R
   R> loginfo("a")
   2016-08-30 16:43:51 INFO::a
   R> loginfo("     a")
   2016-08-30 16:43:55 INFO::a
```

Thanks

**Comment by mfrasca** [comment]
[looks like](https://github.com/mfrasca/r-logging/blob/master/pkg/R/oo.R#L84) it's a feature, I don't recall why I did it this way, it's code I wrote 5 years ago.
if you think it is an undesirable feature, then we can also call it a bug.
we could make it optional, do you want to fork and correct? I will have a look at your work. if you want, I can also help you write unit tests, I prefer adding tests together with new features.

**Comment by yitang** [comment]
emm. I was very attempted to remove those two lines you refereed to. I will fork and add an optional argument.

Thanks,

**Comment by mfrasca** [comment]
solved in master, all tests passing, travis-ci can now build the package.
https://travis-ci.org/mfrasca/r-logging/builds
