### ISSUE TITLE
someone looks at the CRAN issues

### ISSUE THREAD

**Issue by mfrasca** [WLOGSolutions/r-logging#22]
https://cran.r-project.org/web/checks/check_results_logging.html

**Comment by nlbjan1** [comment]
The issue is a bit cryptic to me, I don't see any issues? Everything appears 'OK'.

**Comment by mfrasca** [comment]
I guess I forgot to close this one, or to alert the guys who helped fix them that there was an issue about it.  
Check the https://github.com/mfrasca/r-logging/network page, and in particular this fork https://github.com/WLOGSolutions/r-logging.  
Fixes started with this commit: https://github.com/mfrasca/r-logging/commit/6a0ed6fcaed7838258ee49e44e141cbad7fd1a39
