### ISSUE TITLE
New named loggers should inherit ROOT logger level

### ISSUE THREAD

**Issue by antoine-sachet** [WLOGSolutions/r-logging#24]
Calling a logging function with a new named logger creates a new logger implictly, with `level = INFO`. Is this intended?  I would suggest inheriting the level (and possibly the handlers etc) from `logging.ROOT`.

```r
library("logging")
basicConfig(level = 0)

logdebug("test")
#> 2019-07-11 11:53:30 DEBUG::test

# Current, unexpected behaviour
logdebug("test", logger = "named_logger")
# No output

# Proposed behaviour: named loggers should use the root config by default.
logdebug("test", logger = "named_logger")
#> 2019-07-11 11:53:45 DEBUG::test

ls(logging:::logging.options)
[1] "logging.ROOT"              "logging.ROOT.named_logger"
```

In this example, I would have expected the `logging.ROOT.name_logger` to be set at DEBUG level.

This behaviour can be traced to how `logging::getLogger` creates loggers that are not yet in `logging.options` using `level = namedLevel("INFO")`.

```r 
logging::getLogger <- function (name = "", ...) {
    if (name == "") {
        fullname <- "logging.ROOT"
    }
    else {
        fullname <- paste("logging.ROOT", name, sep = ".")
    }
    if (!exists(fullname, envir = logging.options)) {
        logger <- Logger$new(name = name, handlers = list(), 
            level = namedLevel("INFO"))
        updateOptions.environment(logger, ...)
        logging.options[[fullname]] <- logger
        if (fullname == "logging.ROOT") {
            .basic_config(logger)
        }
    }
    logging.options[[fullname]]
}

**Comment by mfrasca** [comment]
thank you for reporting.  it's a debatable point of view, I think.
- it is indeed intended, that mentioning a logger creates it, implicitly.
- should the new implicitly created logger inherit from its direct parent logger?  or from the root logger?  or should we have a global default logging level?  
- now we have a global default logging level, and you cannot alter it (as far as I recall, you cannot).
- thinking of not breaking configurations for users, I think that it would be safer to introduce (if we didn't do that already) a configuration setting, and have it default to `INFO`.  any other change will surprise users.

as for inheriting handlers, no, that is a mistake.  when a logger gets a message, it will consider it for handling (that means: depending on the level) and will propagate it to its parent logger, and recurse, until the root is reached.  copying handlers from the root or from a parent would mean that equivalent handlers will receive the same message, which will be handled multiple times.

as for where to keep issues: here or on the Polish fork, I never discussed it with the new care-takers of the library.  I do not use R since 2012, so I think, better on the new active fork.

**Comment by ws171913** [comment]
@mfrasca Thank you for responding to this.

I also experienced that misleading behaviour then first started using logging package. Sub-loggers are initialized with INFO level and it is quite difficult to figure out why my sub-logger does not log as far as I forced global level to be DEBUG. 
I've presented new loglevel NOTSET some time ago to mark that sub-logger should inherit parent loglevel. Same loglevel  is default for sub-logger handlers. It was supposed to make using sub-loggers less missleading. Unfortunatly it does not work as expected. I'm fixing it.

Examples:
> logdebug("test")
> loginfo("test")
prints: 
<ts> INFO::test

> logdebug("test", logger = "named_logger")
> loginfo("test", logger = "named_logger")
prints: 
<ts> INFO:named_logger:test

> setLevel("DEBUG")
> logdebug("test", logger = "named_logger")
> loginfo("test", logger = "named_logger")
prints: 
<ts> DEBUG:named_logger:test
<ts> INFO:named_logger:test

> addHandler(writeToConsole, logger = "named_logger")
> logdebug("test", logger = "named_logger")
prints:
<ts> DEBUG:named_logger:test
<ts> DEBUG:named_logger:test
First message is from "named_logger"'s handler, second is from root handler

> addHandler(writeToConsole, level = "INFO", logger = "named_logger")
> logdebug("test", logger = "named_logger")
prints:
<ts> DEBUG:named_logger:test
Message is from root handler, as far as "named_logger"'s handler filtered it out based on own loglevel

**Comment by mfrasca** [comment]
maybe a function that navigates the logger tree, mentioning per logger the level, attached handlers, and their level, could be of help.
I also advise you keep as much as possible a functional compatibility with the Python logging module: that is how I started, and I always relied on the Python's very accurate functional description, to implement whatever I was implementing in this R `logging` package.  this spares me (you) the task of describing this module.

**Comment by mfrasca** [comment]
what you describe in your

> Examples:

looks to me precisely as I would expect.

**Comment by antoine-sachet** [comment]
Thanks for clarifying. I realise now I had misunderstood how the propagation system works. I don't actually care what the level of named logger is, the propagation system is all I need.

The "unexpected behaviour" I describe is _actually a bug_, and the "expected behaviour" is how it should already work, no change required.

Indeed a `logdebug` on a named logger should get printed by the root handler (assuming root level is DEBUG), and it does not on the CRAN version I am using `logging_0.9-106`.

```r
basicConfig(level = 0)
logdebug("test", logger = "named_logger")
# Nothing printed with CRAN version logging_0.9-106
# but it really should be printed by the root writeToConsole handler
```

This is already fixed in the latest version of the package on github. I should have tried that first but I hadn't realised it was a bug. FYI it is also fixed in the latest CRAN version `logging_0.10-108`, but I work in a docker container with a CRAN snapshot from February 2019.

For what it's worth, I do think it makes sense for named loggers to inherit from their parents if not explicitly set, but as @mfrasca it will break systems relying on the default logging level being `INFO`! I would not make the change, not worth it IMO.

**Comment by mfrasca** [comment]
> Indeed a `logdebug` on a named logger should get printed by the root handler (assuming root level is DEBUG), and it does not on the CRAN version I am using `logging_0.9-106`.

also the level of the handler plays the same filtering function.

**Comment by ws171913** [comment]
That should be resolved already
