### ISSUE TITLE
correct membership for 'mfrasca'

### ISSUE THREAD

**Issue by mfrasca** [WLOGSolutions/r-logging#26]
Hi there, I did what we (@ws171913 and myself) had agreed in issue `transfer old issues to new repository (#10)` in your fork, but since part of the plan included removal your fork, we also lost the discussion and description.
what we did:
- you made me part of your organization, which didn't prove sufficient, so you made me 'owner' of it.
- I merged your fork into my base repository
- removed your fork
- moved my base repository to your organization
- forked the repository into my user (as not to break links)

that's it.

I suppose you should now remove me from your organization.

**Comment by ws171913** [comment]
Thank you for you afforts
