### ISSUE TITLE
Less Rigid message coercion/concatenation than sprintf for downstream flexibility

### ISSUE THREAD

**Issue by mstr3336** [WLOGSolutions/r-logging#4]
Thank you for your work on continuing to maintain this package. 
This package is my favourite logging implementation in R, mainly for the convenience of the RC implementation for named loggers, saving me having to specify `name = "name"` in logging statements.

My only gripe is the use of sprintf as a message formatter at the entry point of producing outputs.
I'd prefer it if this format handler were able to be handled by the user, with some supplied default, so we are able to make our own choices about how we're going to produce messages, as I'd like something that passes line-breaks for more readable trace-level dumps.

A usage example might be 
```r
library(glue)
logging::basicConfig()
L <- logging::getLogger()

message <- "Glue strings are presented like f-strings in python"
# Old way
L$info("My message: %s", message)

# Proposed new way
L$formatHandler <- glue::glue
L$info("My message: {message}")
```

Thank you for considering this!

**Comment by ws171913** [comment]
I have objections for presenting new dependencies in the package like glue: I'm using logging due to it is as light as possible. But the way you are proposing does not seem to present any.

I think it is doable and quite nice extension to current functionalities. I'll try to present it on weekend. If I will not stamp on any problems at the beginning of next week there should be new version on CRAN.

btw: from version 0.9 you have no need to call basicConfig before logging gets initialized. You can just log. Default config will be applied automaticaly.

**Comment by mstr3336** [comment]
Good to hear! 
I agree, it's a nice package - It also already more or less allows for custom formatting/parsing dependency injection, except it does this downstream by giving the user their own format/output handlers, but having already passed through sprintf tends to really hamper the flexibility of that.
Also, thank you for the info!

**Comment by ws171913** [comment]
Hello,

I've submitted v0.9-107 onto CRAN. It is currently under verification.

Two new functions have beed added: setMsgComposer and resetMsgComposer (camelcase unfortunatly as rest of logging functions).

With the first one you can set your custom routine to compose log message. Try this:
```
library(glue)
setMsgComposer(function(msg, ...) glue::glue(msg), "MySpecialLogger")

message <- "Glue strings are presented like f-strings in python"
loginfo("My message: {message}", logger = "MySpecialLogger")
# <TS> INFO:MySpecialLogger:My message: Glue strings are presented like f-strings in python

# and root logger still uses default message composer:
loginfo("My message: %s", message)
# <TS> INFO::My message: Glue strings are presented like f-strings in python
```

You are not supposed to alter internals of Logger object (though you can :) ). And setMsgComposer verifies if msg composer signature is correct.

**I would much appreciate if you propose package tutorial update describing this new functionality.**

And please close this ticket as soon as you will be ok with it's behaviour.

**Comment by mstr3336** [comment]
Thank you for the effort! 
If I install from CRAN, am I right to think I'll see these changes? 
I'm happy to write a change to reflect this updated behaviour.

to check - with the interface of `setMsgComposer`

Would it be mandatory to define your input handler as an anonymous function having the signature you defined?
Ie.

`setMsgComposer(function(msg, ...) glue::glue(msg), "MySpecialLogger")`

or would this interface work?

`setMsgComposer(glue::glue, "MySpecialLogger")`

Actually, having typed this I see that the purpose is probably to allow logging statement signatures to be unchanged.

Anyway, I will test this out ASAP and get back to you :)

**Comment by mstr3336** [comment]
Oh, one comment - I notice that though you added an oo interface for the following use case:

```
specialLogger <- logging::getLogger("mySpecialLogger")
specialLogger$getMsgComposer()
```

there is none for
```
specialLogger$setMsgComposer()
```

**Comment by antoine-sachet** [comment]
An important use case is to prevent any unexpected message composition.

```r
setMsgComposer(function(msg, ...) msg)
```

Consider the following use case:

```r
# String ready to be logged
msg <- "New user created: gh%xor"

logging::loginfo(msg)
# Error in sprintf("New user created: gh%xor") : too few arguments
```

This is actually a good attack vector against any service using `logging`. 

For example, I have an API with the following code:
```r
  msg <- glue::glue("{req$REQUEST_METHOD} {req$PATH_INFO} @{req$REMOTE_ADDR} by {req$HTTP_USER_AGENT}")
  logging::loginfo(msg, logger = "api")
```

A maliciously crafted USER AGENT (containing e.g. `%s`) will crash the service!

**Comment by mstr3336** [comment]
> ```r
> # String ready to be logged
> msg <- "New user created: gh%xor"
> 
> logging::loginfo(msg)
> # Error in sprintf("New user created: gh%xor") : too few arguments
> ```
> 
> This is actually a good attack vector against any service using `logging` to log user-provided data without realising that the message is passed through `sprintf` -- and I have been using `logging` for years without realising it!
> 
> For example, I have an API with the following code:
> 
> ```r
>   msg <- glue::glue("{req$REQUEST_METHOD} {req$PATH_INFO} @{req$REMOTE_ADDR} by {req$HTTP_USER_AGENT}")
>   logging::loginfo(msg, logger = "api")
> ```
> 
> A maliciously crafted USER AGENT (containing e.g. `%s`) will crash the service!

Yes, I agree - I've also managed to hardcode messages containing %'s into the format string-  the easy fix to escape that kind of input is to log your messages like this, though:

`logging::loginfo("%s", msg)`

**Comment by mfrasca** [comment]
did you consider cloning the new Python `format` function?  I've seen a VERY compact JavaScript implementation (follows), and [here you have](https://pyformat.info/) a description of the new `format`'s behaviour.

```
         //  format :: String,*... -> String
         var format = create ({});

         //  format.create :: Object -> String,*... -> String
         format.create = create;

         //  format.extend :: Object,Object -> ()
         format.extend = function(prototype, transformers) {
             var $format = create (transformers);
             prototype.format = function() {
                 var args = Array.prototype.slice.call (arguments);
                 args.unshift (this);
                 return $format.apply (this, args);
             };
         };

         /* istanbul ignore if */
         format.extend (String.prototype, {});
```

**Comment by ws171913** [comment]
@mfrasca ability to specify message composers have beed aded some time ago as a responce to requirement of more easier message formatting with use of glue. The same mechanism can be used to format messages alike python format. One can implement whatever message composing functionality she likes also python like format.

If you provide same simple implementation of message composer (without presenting additional dependencies) I would be glad to add it as another default to choose.

**Comment by mfrasca** [comment]
I'm afraid I lost contact with the project and the language. I perfectly agree with the "no additional dependencies" policy, and I'm very happy that you have adopted the project.  if I would be able to write a `format` implementation in R.  mmmmmmmm, doubt it.  it's on a post-it on my wall, though.

**Comment by ws171913** [comment]
Closing issue as no further action is requested
